# per-node configuration
node_name: "${HOSTNAME}"
identifier: "${HOSTNAME}"

telegram:
  bot_token: "<YOUR_BOT_TOKEN>"
  chat_id:   <YOUR_CHAT_ID>

tailscale:
  enabled: true
  endpoint: ""

checks:
  docker_health: true
  zfs_health:    true

logging:
  path: "/mnt/cache/scripts/logs/agent.log"
